### ISSUE TITLE
Github action failed

### ISSUE THREAD

**Issue by f88083** [ZhgChgLi/ZMediumToMarkdown#15]
I followed your [instruction](https://github.com/ZhgChgLi/ZMediumToMarkdown/wiki/How-to-use-Github-Action-as-your-free-&-no-code-Medium-Posts-backup-service). But encountered the following issue. What should I do to fix? Thanks for your response in advance.

![image](https://github.com/ZhgChgLi/ZMediumToMarkdown/assets/56676355/77021b8f-eb07-4993-89e5-cd9dfd4fad44)

**Comment by zhgchgli0718** [comment]
due to the github action access control, need granted repo's action access:
Repo -> Settings -> Actions -> Genral -> 
- Actions permissions -> Allow all actions and reusable workflows ✅ -> Save
- Workflow permissions ->  Read and write permissions ✅ -> Save

and trying re-run again, thank you.

**Comment by f88083** [comment]
> due to the github action access control, need granted repo's action access: Repo -> Settings -> Actions -> Genral ->
> 
> * Actions permissions -> Allow all actions and reusable workflows ✅ -> Save
> * Workflow permissions ->  Read and write permissions ✅ -> Save
> 
> and trying re-run again, thank you.

@zhgchgli0718 Thanks a lot, it works!

**Comment by zhgchgli0718** [comment]
thanks for your report, the [instruction](https://github.com/ZhgChgLi/ZMediumToMarkdown/wiki/How-to-use-Github-Action-as-your-free-&-no-code-Medium-Posts-backup-service) has been updated.
