### ISSUE TITLE
git-auto-commit-action@v4 fails because I changed the README?

### ISSUE THREAD

**Issue by rafapolo** [ZhgChgLi/ZMediumToMarkdown#5]
Run stefanzweifel/git-auto-commit-action@v4
...
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/rafapolo/AreYouSyrious'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)

So, nothing was saved.

**Comment by zhgchgli0718** [comment]
I think it's because you are modifying the readme file during ZMediumToMarkdown is fetching, retry and it'll be fine :)
